version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: cloud
      POSTGRES_USER: cloud
      POSTGRES_PASSWORD: cloud
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: "postgresql://cloud:cloud@db/cloud"
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data:
