version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cloud
      POSTGRES_USER: cloud
      POSTGRES_PASSWORD: cloud
    ports:
      - "5432:5432" 
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: ./app
    environment:
      DATABASE_URL: "postgresql://cloud:cloud@db:5432/database" 
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data:
