version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-projeto}
      POSTGRES_USER:  ${POSTGRES_USER:-projeto}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD:-projeto}
    # ports: 
    # quando for entregar no dockerhub precisa tirar isso e deixar sem
    # usar isso apenas para dev NUNCA em produção
    #  - "5432:5432" 
    # volumes:
    #   - ./db:/docker-entrypoint-initdb.d

  app:
    #build:
    #   context: ./app
    image: beatrizbzack/projeto-cloud-app:latest2
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://projeto:projeto@db:5432/projeto} 
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  db-data:
