version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
    ports: 
    # quando for entregar no dockerhub precisa tirar isso e deixar sem
    # usar isso apenas para dev NUNCA em produção
      - "5432:5432" 
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  app:
    build:
      context: ./app
    environment:
      DATABASE_URL: ${DATABASE_URL} 
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  db-data:
